### PR TITLE
Fix on the GPU Forward Adaptive Euler function

### PR DESCRIPTION
**Pull request by bergolho**
Hello Sachetto,

In this pull request I backtrack the code for the _solve_forward_euler_gpu_adpt()_ function to a previous version. The main issue is related to the removal of a counter variable used in this function to avoid NaN values. In the current version I was facing some NaN troubles with some simulations when using the Trovato model and by reintroducing this counter variable I was able to solve these issues. Could you please check this function again ? Maybe there is a better way that we could tackle this problem instead of using a counter variable.

### CODE REVIEW

**Comment by rsachetto** [comment]
@bergolho This counter makes no sense anymore. Try to remove the dt from the [ode_solver] section in your .ini file. If you do so, the solver will not be bounded to a minimum dt and I think it will solver your problem.

**Comment by bergolho** [comment]
@rsachetto Even by removing the dt argument from the [ode_solver] section the NaN value error persists.

**Comment by rsachetto** [comment]
Can you send me the config file that you are using please?

**Comment by bergolho** [comment]
[rafa_sebastian_only_purkinje_files.zip](https://github.com/rsachetto/MonoAlg3D_C/files/6468319/rafa_sebastian_only_purkinje_files.zip)

**Pull request closed without merging**
